'use client'

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'

type Language = 'ar' | 'en'

// Re-export number formatting utilities for easy component access
export {
  formatNumber,
  formatCurrency,
  formatQuantity,
  formatPrice,
  formatPercentage,
  formatID,
  formatInvoiceNumber,
  formatPhoneNumber,
  formatDateEnglish,
  formatTimeEnglish,
  formatDateTimeEnglish,
  convertArabicNumeralsToEnglish,
  parseNumberSafe,
} from './number-format'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ar: {
    // Branding
    'brand.name': 'سند',
    'brand.tagline': 'Sanad',
    
    // Login & Auth
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'نظام المحاسبة المتكامل',
    'login.username': 'اسم المستخدم',
    'login.password': 'كلمة المرور',
    'login.button': 'تسجيل الدخول',
    'login.error': 'اسم المستخدم أو كلمة المرور غير صحيحة',
    'login.welcome': 'مرحباً بك',
    'login.selectRole': 'اختر الدور',
    'login.enterCredentials': 'يرجى إدخال بيانات الدخول',
    
    // Business Settings / ERPNext
    'businessSettings.title': 'ربط ERPNext',
    'businessSettings.subtitle': 'إعدادات الربط مع نظام ERPNext',
    'businessSettings.businessName': 'اسم المؤسسة',
    'businessSettings.erpNextUrl': 'رابط ERPNext (النطاق)',
    'businessSettings.apiKey': 'مفتاح API',
    'businessSettings.apiSecret': 'كلمة سر API',
    'businessSettings.testConnection': 'اختبار الاتصال',
    'businessSettings.saveConfiguration': 'حفظ الإعدادات',
    'businessSettings.lastSynced': 'آخر مزامنة',
    'businessSettings.connectionSuccess': 'تم الاتصال بنجاح',
    'businessSettings.connectionFailed': 'فشل الاتصال',
    'businessSettings.testing': 'جاري الاختبار...',
    'businessSettings.savedSuccess': 'تم حفظ الإعدادات بنجاح',
    'businessSettings.placeholder.businessName': 'مثال: شركة التقنية المتقدمة',
    'businessSettings.placeholder.url': 'https://your-domain.erpnext.com',
    'businessSettings.placeholder.apiKey': 'أدخل مفتاح API',
    'businessSettings.placeholder.apiSecret': 'أدخل كلمة سر API',
    'businessSettings.never': 'لم تتم المزامنة بعد',
    
    // Navigation
    'nav.dashboard': 'الرئيسية',
    'nav.portal': 'مساحة العمل',
    'nav.pos': 'نقاط البيع (POS)',
    'nav.sales': 'المبيعات (Fatoora)',
    'nav.inventory': 'المخزون',
    'nav.hr': 'الموارد البشرية',
    'nav.analytics': 'التحليلات المتقدمة',
    'nav.users': 'إدارة المستخدمين',
    'nav.security': 'الأمان المالي',
    'nav.integrations': 'إدارة المنصات',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم الرئيسية',
    'dashboard.subtitle': 'نظام المحاسبة المتكامل - سند',
    'security.title': 'حالة الأمان',
    'security.subtitle': 'Security Status',
    'security.encrypted': 'System Encrypted',
    'security.dataEncryption': 'تشفير البيانات نشط',
    'security.twoFactor': 'المصادقة الثنائية مفعلة',
    'security.lastCheck': 'آخر فحص: منذ 5 دقائق',
    'security.advanced': 'حماية متقدمة',
    'security.message': 'نظام الحماية الأمني نشط ويعمل على مدار الساعة',
    
    // Financial
    'finance.revenue': 'إجمالي الإيرادات',
    'finance.vat': 'ضريبة القيمة المضافة',
    'finance.sar': 'ر.س',
    'finance.comparison': 'مقارنة بالشهر الماضي',
    'finance.duethismonth': 'مستحقة هذا الشهر',
    
    // Invoices
    'invoice.recent': 'الفواتير الأخيرة',
    'invoice.subtitle': 'Recent Invoices',
    'invoice.number': 'رقم الفاتورة',
    'invoice.client': 'العميل',
    'invoice.amount': 'المبلغ (ر.س)',
    'invoice.status': 'الحالة',
    'invoice.date': 'التاريخ',
    
    // Sales
    'sales.title': 'إدارة المبيعات',
    'sales.subtitle': 'نظام الفوترة الإلكترونية - Fatoora',
    'sales.totalSales': 'إجمالي المبيعات',
    'sales.invoicesIssued': 'الفواتير الصادرة',
    'sales.avgTransaction': 'متوسط المعاملة',
    'sales.createInvoice': 'إنشاء فاتورة جديدة',
    
    // Inventory
    'inventory.title': 'إدارة المخزون',
    'inventory.subtitle': 'تتبع المنتجات والمخزون',
    'inventory.totalProducts': 'إجمالي المنتجات',
    'inventory.lowStock': 'مخزون منخفض',
    'inventory.stockValue': 'قيمة المخزون',
    'inventory.addProduct': 'إضافة منتج',
    
    // HR
    'hr.title': 'الموارد البشرية',
    'hr.subtitle': 'إدارة الموظفين والرواتب',
    'hr.totalEmployees': 'إجمالي الموظفين',
    'hr.onLeave': 'في إجازة',
    'hr.payrollDue': 'الرواتب المستحقة',
    'hr.addEmployee': 'إضافة موظف',
    
    // Integrations
    'integrations.title': 'إدارة المنصات',
    'integrations.subtitle': 'تكامل أنظمة الدفع والتوصيل',
    'integrations.payments': 'بوابات الدفع',
    'integrations.delivery': 'خدمات التوصيل',
    'integrations.connected': 'متصل',
    'integrations.disconnected': 'غير متصل',
    'integrations.configure': 'إعدادات',
    'integrations.connect': 'ربط',
    'integrations.disconnect': 'فصل',
    'integrations.addPlatform': 'إضافة منصة',
    'integrations.addTerminal': 'إضافة نقطة بيع',
    'integrations.platforms': 'منصات البيع',
    'integrations.terminals': 'نقاط البيع',
    'integrations.platformName': 'اسم المنصة',
    'integrations.terminalName': 'اسم النقطة',
    'integrations.apiKey': 'مفتاح API',
    'integrations.location': 'الموقع',
    'integrations.addPayment': 'إضافة بوابة دفع',
    'integrations.editPayment': 'تعديل بوابة الدفع',
    'integrations.addDelivery': 'إضافة خدمة توصيل',
    'integrations.editDelivery': 'تعديل خدمة التوصيل',
    'integrations.gatewayName': 'اسم البوابة',
    'integrations.serviceName': 'اسم الخدمة',
    'integrations.apiSecret': 'المفتاح السري',
    'integrations.webhookUrl': 'رابط Webhook',
    'integrations.merchantId': 'معرف التاجر',
    'integrations.commission': 'نسبة العمولة',
    'integrations.minOrder': 'الحد الأدنى للطلب',
    'integrations.deliveryTime': 'وقت التوصيل',
    'integrations.coverageArea': 'منطقة التغطية',
    'integrations.status': 'الحالة',
    'integrations.active': 'نشط',
    'integrations.inactive': 'غير نشط',
    'integrations.testMode': 'وضع الاختبار',
    'integrations.liveMode': 'الوضع الحقيقي',
    
    // Security Advanced
    'securityAdv.title': 'الأمان المالي المتقدم',
    'securityAdv.subtitle': 'مراقبة التشفير وإدارة المفاتيح',
    'securityAdv.systemLogs': 'سجلات النظام',
    'securityAdv.encryptionKeys': 'إدارة مفاتيح التشفير',
    'securityAdv.aiEncryption': 'تشفير AI نشط',
    'securityAdv.loginAttempts': 'محاولات تسجيل الدخول',
    'securityAdv.activeSessions': 'الجلسات النشطة',
    'securityAdv.terminal': 'طرفية النظام',
    
    // POS & CRM
    'pos.title': 'نقطة البيع',
    'pos.subtitle': 'نظام البيع الذكي',
    'pos.searchBarcode': 'البحث بالباركود',
    'pos.cart': 'سلة الشراء',
    'pos.subtotal': 'المجموع الفرعي',
    'pos.discount': 'الخصم',
    'pos.vat': 'ضريبة القيمة المضافة',
    'pos.total': 'المجموع الكلي',
    'pos.checkout': 'إتمام الدفع',
    'pos.print': 'طباعة الفاتورة',
    'pos.whatsapp': 'إرسال واتساب',
    'pos.applyDiscount': 'تطبيق خصم',
    'pos.itemDiscount': 'خصم المنتج',
    'pos.percentage': 'نسبة مئوية',
    'pos.fixedAmount': 'مبلغ ثابت',
    'pos.quickPick': 'الاختيار السريع',
    'pos.retailScan': 'وضع المسح',
    'pos.switchMode': 'تبديل الوضع',
    'pos.scanBarcode': 'امسح الباركود أو أدخل رقم الصنف...',
    'pos.rowNum': '#',
    'pos.itemName': 'الصنف',
    'pos.skuBarcode': 'رقم الصنف',
    'pos.unitPrice': 'السعر',
    'pos.quantity': 'الكمية',
    'pos.lineDiscount': 'الخصم',
    'pos.lineTotal': 'المجموع',
    'pos.originalPrice': 'الأصلي',
    
    // Customer & Loyalty
    'crm.customer': 'العميل',
    'crm.registerCustomer': 'تسجيل عميل',
    'crm.name': 'الاسم',
    'crm.phone': 'رقم الهاتف',
    'crm.email': 'البريد الإلكتروني',
    'crm.loyaltyPoints': 'نقاط الولاء',
    'crm.currentPoints': 'النقاط الحالية',
    'crm.redeemPoints': 'استبدال النقاط',
    'crm.pointsRule': 'قاعدة النقاط',
    'crm.pointsPerSAR': 'نقطة لكل ريال',
    'crm.redeemThreshold': 'حد الاستبدال',
    'crm.pointsDiscount': 'نقطة = ريال خصم',
    'crm.lookupCustomer': 'البحث عن عميل',
    'crm.searchByPhone': 'البحث برقم الهاتف',
    'crm.customerNotFound': 'العميل غير موجود',
    'crm.applyPointsDiscount': 'تطبيق خصم النقاط',
    'crm.pointsDeducted': 'النقاط المستخدمة',
    'crm.discountValue': 'قيمة الخصم',
    'crm.remainingPoints': 'النقاط المتبقية',
    
    // Export & Reports
    'export.title': 'تصدير البيانات',
    'export.csv': 'تصدير CSV',
    'export.pdf': 'تصدير PDF',
    'export.timestamp': 'التاريخ والوقت',
    
    // Promotions
    'promo.title': 'العروض الترويجية',
    'promo.buyOneGetOne': 'اشتر واحد واحصل على آخر',
    'promo.percentOff': 'خصم على الثالث',
    'promo.active': 'نشط',
    'promo.create': 'إنشاء عرض',
    
    // ZATCA & Invoice Details
    'invoice.storeName': 'سند للمحاسبة',
    'invoice.vatNumber': 'الرقم الضريبي',
    'invoice.vatId': '300123456700003',
    'invoice.qrCode': 'رمز QR',
    'invoice.totalDiscount': 'إجمالي الخصم',
    'invoice.grandTotal': 'المجموع النهائي',
    'invoice.paymentSuccess': 'تمت العملية بنجاح',
    'invoice.selectPayment': 'اختر طريقة الدفع',
    'invoice.invoiceDetails': 'تفاصيل الفاتورة',
    'invoice.amountReceived': 'المبلغ المستلم',
    'invoice.changeDue': 'المبلغ المتبقي',
    'invoice.cashierHelper': 'حاسبة الصراف',
    'invoice.invoiceTotal': 'إجمالي الفاتورة',
    
    // Settings & Profile
    'settings.title': 'الإعدادات',
    'settings.general': 'إعدادات عامة',
    'settings.branchName': 'اسم الفرع',
    'settings.companyLogo': 'شعار الشركة',
    'settings.uploadLogo': 'رفع شعار',
    'settings.removeLogo': 'حذف الشعار',
    'settings.logoHint': 'يظهر الشعار في صفحة الدخول والقائمة الجانبية والفواتير',
    'settings.resetSystem': 'إعادة ضبط النظام',
    'settings.resetWarning': 'هل أنت متأكد؟ سيتم حذف جميع البيانات وإعادة تشغيل النظام من جديد.',
    'settings.resetSuccess': 'تم إعادة ضبط النظام بنجاح',
    'settings.save': 'حفظ',
    'settings.close': 'إغلاق',
    'profile.title': 'الملف الشخصي',
    'profile.info': 'معلومات الملف',
    'profile.subscription': 'حالة الاشتراك',
    'profile.securitySettings': 'إعدادات الأمان',
    'profile.logout': 'تسجيل الخروج',
    
    // Employee & RBAC
    'employee.title': 'الموظفين والصلاحيات',
    'employee.add': 'إضافة موظف',
    'employee.permissions': 'الصلاحيات',
    'employee.role': 'الدور',
    'employee.accessDashboard': 'الرئيسية (Dashboard)',
    'employee.accessPos': 'نقاط البيع (POS)',
    'employee.accessSales': 'المبيعات (Fatoora)',
    'employee.accessInventory': 'المخزون (Inventory)',
    'employee.accessHR': 'الموارد البشرية (HR)',
    'employee.accessSecurity': 'الأمان المالي (Security)',
    'employee.accessErpnext': 'ربط ERPNext',
    'employee.accessIntegrations': 'إدارة المنصات (Platforms)',
    'employee.accessEmployees': 'الموظفين والصلاحيات',
    'employee.accessPromotions': 'إدارة العروض (Promotions)',
    
    // Promotions Management
    'promo.management': 'إدارة العروض',
    'promo.enableAll': 'تفعيل جميع العروض',
    'promo.disableAll': 'تعطيل جميع العروض',
    'promo.productDiscount': 'خصم المنتج',
    'promo.selectProduct': 'اختر المنتج',
    'promo.specialDeals': 'عروض خاصة',
    'promo.expired': 'منتهي',
    'promo.buy2Get1': 'اشتر 2 واحصل على 1 مجاناً',
    
    // Product Management
    'product.addNew': 'إضافة منتج جديد',
    'product.name': 'اسم المنتج',
    'product.sku': 'رمز المنتج (SKU)',
    'product.category': 'الفئة',
    'product.costPrice': 'سعر التكلفة',
    'product.sellingPrice': 'سعر البيع',
    'product.edit': 'تعديل المنتج',
    'product.delete': 'حذف المنتج',

    // HR Attendance System
    'hr.attendance': 'نظام الحضور',
    'hr.attendanceSubtitle': 'تسجيل الدخول والخروج - مزامنة ERPNext وتنبيهات تيليجرام',
    'hr.checkIn': 'تسجيل دخول',
    'hr.checkOut': 'تسجيل خروج',
    'hr.checkedIn': 'تم تسجيل الدخول',
    'hr.checkedOut': 'تم تسجيل الخروج',
    'hr.status': 'الحالة',
    'hr.time': 'الوقت',
    'hr.date': 'التاريخ',
    'hr.branch': 'الفرع',
    'hr.employeeDirectory': 'دليل الموظفين',
    'hr.searchEmployees': 'البحث عن موظف...',
    'hr.designation': 'المسمى الوظيفي',
    'hr.department': 'القسم',
    'hr.payroll': 'كشف الرواتب',
    'hr.salarySlips': 'قسائم الرواتب',
    'hr.leaveApplication': 'طلب إجازة',
    'hr.leaveType': 'نوع الإجازة',
    'hr.vacation': 'إجازة سنوية',
    'hr.sickLeave': 'إجازة مرضية',
    'hr.fromDate': 'من تاريخ',
    'hr.toDate': 'إلى تاريخ',
    'hr.reason': 'السبب',
    'hr.submitLeave': 'تقديم الطلب',
    'hr.todayAttendance': 'حضور اليوم',
    'hr.attendanceLog': 'سجل الحضور',
    'hr.totalPresent': 'الحضور',
    'hr.totalAbsent': 'الغياب',
    'hr.lateArrivals': 'التأخير',
    'hr.earlyDepartures': 'الخروج المبكر',
    'hr.employee': 'الموظف',
    'hr.action': 'الإجراء',
    'hr.notificationSent': 'تم إرسال التنبيه',
    'hr.erpSynced': 'تمت المزامنة مع ERPNext',
    'hr.break': 'بريك',
    'hr.permission': 'استئذان',
    'hr.return': 'عودة',
    'hr.onBreak': 'في استراحة',
    'hr.onPermission': 'مستأذن',
    'hr.working': 'يعمل',
    'hr.absent': 'غائب',
    'hr.autoCheckIn': 'تم تسجيل الدخول تلقائياً',
    'hr.autoCheckInDesc': 'تم تسجيل حضورك تلقائياً عند دخول النظام',
    'hr.myAttendance': 'حضوري',
    'hr.myLeaves': 'الإجازات',
    'hr.myPayroll': 'الرواتب',
    'hr.teamStatus': 'حالة الفريق',
    'hr.pendingApprovals': 'الموافقات المعلقة',
    'hr.approvalQueue': 'طلبات الموافقة',
    'hr.approve': 'موافقة',
    'hr.reject': 'رفض',
    'hr.approved': 'موافق عليه',
    'hr.rejected': 'مرفوض',
    'hr.pending': 'قيد الانتظار',
    'hr.confirmTime': 'تأكيد الوقت',
    'hr.actualTime': 'الوقت الفعلي',
    'hr.requestType': 'نوع الطلب',
    'hr.leaveRequest': 'طلب إجازة',
    'hr.permissionRequest': 'طلب استئذان',
    'hr.breakRequest': 'طلب استراحة',
    'hr.deduction': 'خصم',
    'hr.incentive': 'إضافة',
    'hr.payrollAdjustment': 'تعديل الراتب',
    'hr.adjustmentAmount': 'مبلغ التعديل',
    'hr.adjustmentReason': 'سبب التعديل',
    'hr.applyAdjustment': 'تطبيق التعديل',
    'hr.managerView': 'عرض المدير',
    'hr.employeeView': 'عرض الموظف',
    'hr.viewAs': 'عرض كـ',
    'hr.switchView': 'تبديل العرض',
    'hr.myDashboard': 'لوحتي',
    'hr.teamDashboard': 'لوحة الفريق',
    'hr.branchStatus': 'حالة الفرع',
    'hr.globalAnalytics': 'التحليلات الشاملة',
    'hr.allBranches': 'جميع الفروع',
    'hr.myBranch': 'فرعي',
    'hr.branchFilter': 'تصفية حسب الفرع',
    'hr.hrManagerRole': 'مدير موارد بشرية',
    'hr.branchManagerRole': 'مدير فرع',
    'hr.fullCompanyAccess': 'وصول كامل لجميع الفروع',
    'hr.branchLevelAccess': 'وصول على مستوى الفرع فقط',
    'hr.attendanceTrends': 'اتجاهات الحضور',
    'hr.branchComparison': 'مقارنة الفروع',
    'hr.roleManagement': 'إدارة الأدوار',

    // Permissions Management
    'permissions.title': 'الأدوار والصلاحيات',
    'permissions.subtitle': 'إدارة صلاحيات الوصول للمستخدمين والأدوار',
    'permissions.selectRole': 'اختر الدور',
    'permissions.moduleName': 'الوحدة',
    'permissions.permissionName': 'الصلاحية',
    'permissions.status': 'الحالة',
    'permissions.enabled': 'مفعل',
    'permissions.disabled': 'معطل',
    'permissions.selectAll': 'تحديد الكل',
    'permissions.revokeAll': 'إلغاء الكل',
    'permissions.saveChanges': 'حفظ التغييرات',
    'permissions.changesSaved': 'تم حفظ التغييرات',
    'permissions.syncedToERPNext': 'تمت المزامنة مع ERPNext',
    'permissions.roleUpdated': 'تم تحديث صلاحيات الدور',
    'permissions.admin': 'مدير النظام',
    'permissions.hrManager': 'مدير موارد بشرية',
    'permissions.branchManager': 'مدير فرع',
    'permissions.cashier': 'كاشير',
    'permissions.employee': 'موظف',
    'permissions.moduleSales': 'المبيعات',
    'permissions.moduleInventory': 'المخزون',
    'permissions.moduleHR': 'الموارد البشرية',
    'permissions.moduleSettings': 'الإعدادات',
    'permissions.forbidden': 'غير مصرح',
    'permissions.forbiddenMessage': 'ليس لديك صلاحية للوصول إلى هذه الصفحة',
    'permissions.accessDenied': 'تم رفض الوصول',
    'permissions.description': 'الوصف',
    'permissions.actions': 'الإجراءات',
    'permissions.active': 'نشط',
    'permissions.revoked': 'ملغي',

    // Telegram Settings
    'telegram.title': 'إعدادات تيليجرام',
    'telegram.subtitle': 'ربط إشعارات الحضور مع مجموعة تيليجرام',
    'telegram.botToken': 'رمز بوت تيليجرام (Bot Token)',
    'telegram.chatId': 'معرف المجموعة (Chat ID)',
    'telegram.testConnection': 'اختبار الاتصال',
    'telegram.testSuccess': 'تم الاتصال بنجاح - تم إرسال رسالة تجريبية',
    'telegram.testFailed': 'فشل الاتصال - تحقق من البيانات',
    'telegram.guide': 'دليل الإعداد',
    'telegram.guideStep1': '1. افتح تيليجرام وابحث عن @BotFather',
    'telegram.guideStep2': '2. أرسل الأمر /newbot واتبع التعليمات',
    'telegram.guideStep3': '3. انسخ رمز البوت (Bot Token) والصقه هنا',
    'telegram.guideStep4': '4. أضف البوت إلى مجموعة تيليجرام',
    'telegram.guideStep5': '5. ابحث عن @GetIDsBot للحصول على معرف المجموعة',
    'telegram.guideStep6': '6. أرسل /start في المجموعة بعد إضافة @GetIDsBot',
    'telegram.enabled': 'تنبيهات تيليجرام مفعلة',
    'telegram.disabled': 'تنبيهات تيليجرام معطلة',

    // System Settings
    'systemSettings.title': 'إعدادات النظام',
    'systemSettings.subtitle': 'إعدادات ERPNext وتيليجرام',
    'systemSettings.autoSendInvoice': 'إرسال الفاتورة تلقائياً عبر تيليجرام',
    'systemSettings.autoSendInvoiceDesc': 'عند التفعيل، سيتم إرسال ملخص الفاتورة مع QR إلى المجموعة',

    // Invoice Share & Print
    'invoice.printAndShare': 'طباعة ومشاركة',
    'invoice.shareViaWhatsApp': 'إرسال عبر واتساب',
    'invoice.shareViaTelegram': 'إرسال عبر تيليجرام',
    'invoice.zatcaQR': 'رمز الاستجابة السريعة ZATCA',
    'invoice.scanQR': 'امسح الرمز للتحقق من الفاتورة',
    'invoice.shareSuccess': 'تم إرسال الفاتورة بنجاح',
    'invoice.shareFailed': 'فشل إرسال الفاتورة',
    'invoice.whatsappTemplate': 'عزيزي العميل، شكراً لتسوقكم من سند. رقم فاتورتكم هو {id}. المبلغ الإجمالي: {total} ر.س',
    'invoice.telegramSent': 'تم إرسال الفاتورة إلى تيليجرام',
    'invoice.invoiceNumber': 'رقم الفاتورة',
    'invoice.close': 'إغلاق',
    'invoice.newSale': 'عملية جديدة',
  },
  en: {
  // Branding
  'brand.name': 'Sanad',
  'brand.tagline': 'سند',
  
  // Login & Auth
  'login.title': 'Login',
  'login.subtitle': 'Integrated Accounting System',
  'login.username': 'Username',
  'login.password': 'Password',
  'login.button': 'Sign In',
  'login.error': 'Invalid username or password',
  'login.welcome': 'Welcome',
  'login.selectRole': 'Select Role',
  'login.enterCredentials': 'Please enter your credentials',
  
  // Business Settings / ERPNext
  'businessSettings.title': 'ERPNext Integration',
  'businessSettings.subtitle': 'Configure ERPNext Integration',
  'businessSettings.businessName': 'Business Name',
  'businessSettings.erpNextUrl': 'ERPNext URL (Domain)',
  'businessSettings.apiKey': 'API Key',
  'businessSettings.apiSecret': 'API Secret',
  'businessSettings.testConnection': 'Test Connection',
  'businessSettings.saveConfiguration': 'Save Configuration',
  'businessSettings.lastSynced': 'Last Synced',
  'businessSettings.connectionSuccess': 'Connection Successful',
  'businessSettings.connectionFailed': 'Connection Failed',
  'businessSettings.testing': 'Testing...',
  'businessSettings.savedSuccess': 'Configuration saved successfully',
  'businessSettings.placeholder.businessName': 'e.g., Advanced Tech Company',
  'businessSettings.placeholder.url': 'https://your-domain.erpnext.com',
  'businessSettings.placeholder.apiKey': 'Enter your API Key',
  'businessSettings.placeholder.apiSecret': 'Enter your API Secret',
  'businessSettings.never': 'Never synced',
  
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.portal': 'My Workspace',
    'nav.pos': 'Point of Sale (POS)',
    'nav.sales': 'Sales (Fatoora)',
    'nav.inventory': 'Inventory',
    'nav.hr': 'Human Resources',
    'nav.analytics': 'Advanced Analytics',
    'nav.users': 'User Management',
    'nav.security': 'Financial Security',
    'nav.integrations': 'Platform Management',
    
    // Dashboard
    'dashboard.title': 'Main Dashboard',
    'dashboard.subtitle': 'Integrated Accounting System - Sanad',
    'security.title': 'Security Status',
    'security.subtitle': 'حالة الأمان',
    'security.encrypted': 'System Encrypted',
    'security.dataEncryption': 'Data encryption active',
    'security.twoFactor': 'Two-factor authentication enabled',
    'security.lastCheck': 'Last check: 5 minutes ago',
    'security.advanced': 'Advanced Protection',
    'security.message': 'Security system is active 24/7',
    
    // Financial
    'finance.revenue': 'Total Revenue',
    'finance.vat': 'VAT Due',
    'finance.sar': 'SAR',
    'finance.comparison': 'Compared to last month',
    'finance.duethismonth': 'Due this month',
    
    // Invoices
    'invoice.recent': 'Recent Invoices',
    'invoice.subtitle': 'الفواتير الأخيرة',
    'invoice.number': 'Invoice #',
    'invoice.client': 'Client',
    'invoice.amount': 'Amount (SAR)',
    'invoice.status': 'Status',
    'invoice.date': 'Date',
    
    // Sales
    'sales.title': 'Sales Management',
    'sales.subtitle': 'Electronic Invoicing System - Fatoora',
    'sales.totalSales': 'Total Sales',
    'sales.invoicesIssued': 'Invoices Issued',
    'sales.avgTransaction': 'Avg Transaction',
    'sales.createInvoice': 'Create New Invoice',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.subtitle': 'Track Products and Stock',
    'inventory.totalProducts': 'Total Products',
    'inventory.lowStock': 'Low Stock',
    'inventory.stockValue': 'Stock Value',
    'inventory.addProduct': 'Add Product',
    
    // HR
    'hr.title': 'Human Resources',
    'hr.subtitle': 'Employee and Payroll Management',
    'hr.totalEmployees': 'Total Employees',
    'hr.onLeave': 'On Leave',
    'hr.payrollDue': 'Payroll Due',
    'hr.addEmployee': 'Add Employee',
    
    // Integrations
    'integrations.title': 'Platform Management',
    'integrations.subtitle': 'Payment & Delivery Integration',
    'integrations.payments': 'Payment Gateways',
    'integrations.delivery': 'Delivery Services',
    'integrations.connected': 'Connected',
    'integrations.disconnected': 'Disconnected',
    'integrations.configure': 'Configure',
    'integrations.connect': 'Connect',
    'integrations.disconnect': 'Disconnect',
    'integrations.addPlatform': 'Add Platform',
    'integrations.addTerminal': 'Add POS Terminal',
    'integrations.platforms': 'Sales Platforms',
    'integrations.terminals': 'POS Terminals',
    'integrations.platformName': 'Platform Name',
    'integrations.terminalName': 'Terminal Name',
    'integrations.apiKey': 'API Key',
    'integrations.location': 'Location',
    'integrations.addPayment': 'Add Payment Gateway',
    'integrations.editPayment': 'Edit Payment Gateway',
    'integrations.addDelivery': 'Add Delivery Service',
    'integrations.editDelivery': 'Edit Delivery Service',
    'integrations.gatewayName': 'Gateway Name',
    'integrations.serviceName': 'Service Name',
    'integrations.apiSecret': 'API Secret',
    'integrations.webhookUrl': 'Webhook URL',
    'integrations.merchantId': 'Merchant ID',
    'integrations.commission': 'Commission Rate',
    'integrations.minOrder': 'Minimum Order',
    'integrations.deliveryTime': 'Delivery Time',
    'integrations.coverageArea': 'Coverage Area',
    'integrations.status': 'Status',
    'integrations.active': 'Active',
    'integrations.inactive': 'Inactive',
    'integrations.testMode': 'Test Mode',
    'integrations.liveMode': 'Live Mode',
    
    // Security Advanced
    'securityAdv.title': 'Advanced Financial Security',
    'securityAdv.subtitle': 'Encryption Monitoring & Key Management',
    'securityAdv.systemLogs': 'System Logs',
    'securityAdv.encryptionKeys': 'Encryption Key Management',
    'securityAdv.aiEncryption': 'AI Encryption Active',
    'securityAdv.loginAttempts': 'Login Attempts',
    'securityAdv.activeSessions': 'Active Sessions',
    'securityAdv.terminal': 'System Terminal',
    
    // POS & CRM
    'pos.title': 'Point of Sale',
    'pos.subtitle': 'Smart Retail System',
    'pos.searchBarcode': 'Search by Barcode',
    'pos.cart': 'Shopping Cart',
    'pos.subtotal': 'Subtotal',
    'pos.discount': 'Discount',
    'pos.vat': 'VAT',
    'pos.total': 'Total',
    'pos.checkout': 'Checkout',
    'pos.print': 'Print Invoice',
    'pos.whatsapp': 'Send via WhatsApp',
    'pos.applyDiscount': 'Apply Discount',
    'pos.itemDiscount': 'Item Discount',
    'pos.percentage': 'Percentage',
    'pos.fixedAmount': 'Fixed Amount',
    'pos.quickPick': 'Quick Pick',
    'pos.retailScan': 'Retail Scan',
    'pos.switchMode': 'Switch Mode',
    'pos.scanBarcode': 'Scan barcode or enter SKU...',
    'pos.rowNum': '#',
    'pos.itemName': 'Item',
    'pos.skuBarcode': 'SKU / Barcode',
    'pos.unitPrice': 'Price',
    'pos.quantity': 'Qty',
    'pos.lineDiscount': 'Discount',
    'pos.lineTotal': 'Total',
    'pos.originalPrice': 'Original',
    
    // Customer & Loyalty
    'crm.customer': 'Customer',
    'crm.registerCustomer': 'Register Customer',
    'crm.name': 'Name',
    'crm.phone': 'Phone Number',
    'crm.email': 'Email',
    'crm.loyaltyPoints': 'Loyalty Points',
    'crm.currentPoints': 'Current Points',
    'crm.redeemPoints': 'Redeem Points',
    'crm.pointsRule': 'Points Rule',
    'crm.pointsPerSAR': 'Points per SAR',
    'crm.redeemThreshold': 'Redeem Threshold',
    'crm.pointsDiscount': 'Points = SAR Discount',
    'crm.lookupCustomer': 'Customer Lookup',
    'crm.searchByPhone': 'Search by Phone Number',
    'crm.customerNotFound': 'Customer not found',
    'crm.applyPointsDiscount': 'Apply Points Discount',
    'crm.pointsDeducted': 'Points Used',
    'crm.discountValue': 'Discount Value',
    'crm.remainingPoints': 'Remaining Points',
    
    // Export & Reports
    'export.title': 'Export Data',
    'export.csv': 'Export CSV',
    'export.pdf': 'Export PDF',
    'export.timestamp': 'Date & Time',
    
    // Promotions
    'promo.title': 'Promotional Offers',
    'promo.buyOneGetOne': 'Buy One Get One',
    'promo.percentOff': '50% Off on 3rd Item',
    'promo.active': 'Active',
    'promo.create': 'Create Offer',
    
    // ZATCA & Invoice Details
    'invoice.storeName': 'Sanad Accounting',
    'invoice.vatNumber': 'VAT Number',
    'invoice.vatId': '300123456700003',
    'invoice.qrCode': 'QR Code',
    'invoice.totalDiscount': 'Total Discount',
    'invoice.grandTotal': 'Grand Total',
    'invoice.paymentSuccess': 'Payment Successful',
    'invoice.selectPayment': 'Select Payment Method',
    'invoice.invoiceDetails': 'Invoice Details',
    'invoice.amountReceived': 'Amount Received',
    'invoice.changeDue': 'Change Due',
    'invoice.cashierHelper': 'Cashier Helper',
    'invoice.invoiceTotal': 'Invoice Total',
    
    // Settings & Profile
    'settings.title': 'Settings',
    'settings.general': 'General Settings',
    'settings.branchName': 'Branch Name',
    'settings.companyLogo': 'Company Logo',
    'settings.uploadLogo': 'Upload Logo',
    'settings.removeLogo': 'Remove Logo',
    'settings.logoHint': 'Logo appears on the login page, sidebar, and invoices',
    'settings.resetSystem': 'Reset System',
    'settings.resetWarning': 'Are you sure? All data will be deleted and the system will restart.',
    'settings.resetSuccess': 'System reset successfully',
    'settings.save': 'Save',
    'settings.close': 'Close',
    'profile.title': 'User Profile',
    'profile.info': 'Profile Info',
    'profile.subscription': 'Subscription Status',
    'profile.securitySettings': 'Security Settings',
    'profile.logout': 'Logout',
    
    // Employee & RBAC
    'employee.title': 'Employees & Permissions',
    'employee.add': 'Add Employee',
    'employee.permissions': 'Permissions',
    'employee.role': 'Role',
    'employee.accessDashboard': 'Dashboard',
    'employee.accessPos': 'Point of Sale (POS)',
    'employee.accessSales': 'Sales (Fatoora)',
    'employee.accessInventory': 'Inventory',
    'employee.accessHR': 'Human Resources (HR)',
    'employee.accessSecurity': 'Financial Security',
    'employee.accessErpnext': 'ERPNext Integration',
    'employee.accessIntegrations': 'Platform Management',
    'employee.accessEmployees': 'Employees & Permissions',
    'employee.accessPromotions': 'Promotions Management',
    
    // Promotions Management
    'promo.management': 'Offers Management',
    'promo.enableAll': 'Enable All Offers',
    'promo.disableAll': 'Disable All Offers',
    'promo.productDiscount': 'Product Discount',
    'promo.selectProduct': 'Select Product',
    'promo.specialDeals': 'Special Deals',
    'promo.expired': 'Expired',
    'promo.buy2Get1': 'Buy 2 Get 1 Free',
    
    // Product Management
    'product.addNew': 'Add New Product',
    'product.name': 'Product Name',
    'product.sku': 'SKU Code',
    'product.category': 'Category',
    'product.costPrice': 'Cost Price',
    'product.sellingPrice': 'Selling Price',
    'product.edit': 'Edit Product',
    'product.delete': 'Delete Product',

    // HR Attendance System
    'hr.attendance': 'Attendance System',
    'hr.attendanceSubtitle': 'Check-in/Out - ERPNext Sync & Telegram Alerts',
    'hr.checkIn': 'Check In',
    'hr.checkOut': 'Check Out',
    'hr.checkedIn': 'Checked In',
    'hr.checkedOut': 'Checked Out',
    'hr.status': 'Status',
    'hr.time': 'Time',
    'hr.date': 'Date',
    'hr.branch': 'Branch',
    'hr.employeeDirectory': 'Employee Directory',
    'hr.searchEmployees': 'Search employees...',
    'hr.designation': 'Designation',
    'hr.department': 'Department',
    'hr.payroll': 'Payroll',
    'hr.salarySlips': 'Salary Slips',
    'hr.leaveApplication': 'Leave Application',
    'hr.leaveType': 'Leave Type',
    'hr.vacation': 'Annual Leave',
    'hr.sickLeave': 'Sick Leave',
    'hr.fromDate': 'From Date',
    'hr.toDate': 'To Date',
    'hr.reason': 'Reason',
    'hr.submitLeave': 'Submit Request',
    'hr.todayAttendance': "Today's Attendance",
    'hr.attendanceLog': 'Attendance Log',
    'hr.totalPresent': 'Present',
    'hr.totalAbsent': 'Absent',
    'hr.lateArrivals': 'Late Arrivals',
    'hr.earlyDepartures': 'Early Departures',
    'hr.employee': 'Employee',
    'hr.action': 'Action',
    'hr.notificationSent': 'Notification Sent',
    'hr.erpSynced': 'Synced with ERPNext',
    'hr.break': 'Break',
    'hr.permission': 'Permission',
    'hr.return': 'Return',
    'hr.onBreak': 'On Break',
    'hr.onPermission': 'On Permission',
    'hr.working': 'Working',
    'hr.absent': 'Absent',
    'hr.autoCheckIn': 'Auto Check-in Successful',
    'hr.autoCheckInDesc': 'Your attendance was recorded automatically upon login',
    'hr.myAttendance': 'My Attendance',
    'hr.myLeaves': 'Leaves',
    'hr.myPayroll': 'Salaries',
    'hr.teamStatus': 'Team Status',
    'hr.pendingApprovals': 'Pending Approvals',
    'hr.approvalQueue': 'Approval Queue',
    'hr.approve': 'Approve',
    'hr.reject': 'Reject',
    'hr.approved': 'Approved',
    'hr.rejected': 'Rejected',
    'hr.pending': 'Pending',
    'hr.confirmTime': 'Confirm Time',
    'hr.actualTime': 'Actual Time',
    'hr.requestType': 'Request Type',
    'hr.leaveRequest': 'Leave Request',
    'hr.permissionRequest': 'Permission Request',
    'hr.breakRequest': 'Break Request',
    'hr.deduction': 'Deduction',
    'hr.incentive': 'Incentive',
    'hr.payrollAdjustment': 'Payroll Adjustment',
    'hr.adjustmentAmount': 'Adjustment Amount',
    'hr.adjustmentReason': 'Adjustment Reason',
    'hr.applyAdjustment': 'Apply Adjustment',
    'hr.managerView': 'Manager View',
    'hr.employeeView': 'Employee View',
    'hr.viewAs': 'View As',
    'hr.switchView': 'Switch View',
    'hr.myDashboard': 'My Dashboard',
    'hr.teamDashboard': 'Team Dashboard',
    'hr.branchStatus': 'Branch Status',
    'hr.globalAnalytics': 'Global Analytics',
    'hr.allBranches': 'All Branches',
    'hr.myBranch': 'My Branch',
    'hr.branchFilter': 'Branch Filter',
    'hr.hrManagerRole': 'HR Manager',
    'hr.branchManagerRole': 'Branch Manager',
    'hr.fullCompanyAccess': 'Full Company Access',
    'hr.branchLevelAccess': 'Branch Level Access Only',
    'hr.attendanceTrends': 'Attendance Trends',
    'hr.branchComparison': 'Branch Comparison',
    'hr.roleManagement': 'Role Management',

    // Permissions Management
    'permissions.title': 'Roles & Permissions',
    'permissions.subtitle': 'Manage user access rights and role permissions',
    'permissions.selectRole': 'Select Role',
    'permissions.moduleName': 'Module',
    'permissions.permissionName': 'Permission',
    'permissions.status': 'Status',
    'permissions.enabled': 'Enabled',
    'permissions.disabled': 'Disabled',
    'permissions.selectAll': 'Select All',
    'permissions.revokeAll': 'Revoke All',
    'permissions.saveChanges': 'Save Changes',
    'permissions.changesSaved': 'Changes Saved',
    'permissions.syncedToERPNext': 'Synced to ERPNext',
    'permissions.roleUpdated': 'Role permissions updated',
    'permissions.admin': 'System Admin',
    'permissions.hrManager': 'HR Manager',
    'permissions.branchManager': 'Branch Manager',
    'permissions.cashier': 'Cashier',
    'permissions.employee': 'Employee',
    'permissions.moduleSales': 'Sales',
    'permissions.moduleInventory': 'Inventory',
    'permissions.moduleHR': 'Human Resources',
    'permissions.moduleSettings': 'Settings',
    'permissions.forbidden': 'Forbidden',
    'permissions.forbiddenMessage': 'You do not have permission to access this page',
    'permissions.accessDenied': 'Access Denied',
    'permissions.description': 'Description',
    'permissions.actions': 'Actions',
    'permissions.active': 'Active',
    'permissions.revoked': 'Revoked',

    // Telegram Settings
    'telegram.title': 'Telegram Settings',
    'telegram.subtitle': 'Connect attendance alerts to a Telegram group',
    'telegram.botToken': 'Telegram Bot Token',
    'telegram.chatId': 'Chat ID',
    'telegram.testConnection': 'Test Connection',
    'telegram.testSuccess': 'Connection successful - Test message sent',
    'telegram.testFailed': 'Connection failed - Verify credentials',
    'telegram.guide': 'Setup Guide',
    'telegram.guideStep1': '1. Open Telegram and search for @BotFather',
    'telegram.guideStep2': '2. Send /newbot and follow the instructions',
    'telegram.guideStep3': '3. Copy the Bot Token and paste it here',
    'telegram.guideStep4': '4. Add the bot to your Telegram group',
    'telegram.guideStep5': '5. Search for @GetIDsBot to get the Chat ID',
    'telegram.guideStep6': '6. Send /start in the group after adding @GetIDsBot',
    'telegram.enabled': 'Telegram alerts enabled',
    'telegram.disabled': 'Telegram alerts disabled',

    // System Settings
    'systemSettings.title': 'System Settings',
    'systemSettings.subtitle': 'ERPNext & Telegram Configuration',
    'systemSettings.autoSendInvoice': 'Auto-send invoice via Telegram',
    'systemSettings.autoSendInvoiceDesc': 'When enabled, invoice summary with QR will be sent to the group',

    // Invoice Share & Print
    'invoice.printAndShare': 'Print & Share',
    'invoice.shareViaWhatsApp': 'Send via WhatsApp',
    'invoice.shareViaTelegram': 'Send via Telegram',
    'invoice.zatcaQR': 'ZATCA QR Code',
    'invoice.scanQR': 'Scan code to verify invoice',
    'invoice.shareSuccess': 'Invoice sent successfully',
    'invoice.shareFailed': 'Failed to send invoice',
    'invoice.whatsappTemplate': 'Dear Customer, thank you for shopping at Sanad. Your invoice number is {id}. Grand Total: {total} SAR',
    'invoice.telegramSent': 'Invoice sent to Telegram',
    'invoice.invoiceNumber': 'Invoice Number',
    'invoice.close': 'Close',
    'invoice.newSale': 'New Sale',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar')

  useEffect(() => {
    // Update document direction and lang when language changes
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = language
    
    // Update body class for font switching
    if (language === 'ar') {
      document.body.classList.add('font-arabic')
      document.body.classList.remove('font-english')
    } else {
      document.body.classList.add('font-english')
      document.body.classList.remove('font-arabic')
    }
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ar] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
